export const CREATE_RESTAURENT_REQUEST="CREATE_RESTAURENT_REQUEST";
export const CREATE_RESTAURENT_SUCCESS="CREATE_RESTAURENT_SUCCESS";
export const CREATE_RESTAURENT_FAILURE="CREATE_RESTAURENT_FAILURE";

export const GET_ALL_RESTAURENTS_REQUEST="GET_ALL_RESTAURENTS_REQUEST";
export const GET_ALL_RESTAURENTS_SUCCESS="GET_ALL_RESTAURENTS_SUCCESS";
export const GET_ALL_RESTAURENTS_FAILURE="GET_ALL_RESTAURENTS_FAILURE";

export const DELETE_RESTAURENT_REQUEST="DELETE_RESTAURENT_REQUEST";
export const DELETE_RESTAURENT_SUCCESS="DELETE_RESTAURENT_SUCCESS";
export const DELETE_RESTAURENT_FAILURE="DELETE_RESTAURENT_FAILURE";

export const UPDATE_RESTAURENT_REQUEST="UPDATE_RESTAURENT_REQUEST";
export const UPDATE_RESTAURENT_SUCCESS="UPDATE_RESTAURENT_SUCCESS";
export const UPDATE_RESTAURENT_FAILURE="UPDATE_RESTAURENT_FAILURE";

export const GET_RESTAURENT_BY_ID_REQUEST="GET_RESTAURENT_BY_ID_REQUEST";
export const GET_RESTAURENT_BY_ID_SUCCESS="GET_RESTAURENT_BY_ID_SUCCESS";
export const GET_RESTAURENT_BY_ID_FAILURE="GET_RESTAURENT_BY_ID_FAILURE";

export const GET_RESTAURENT_BY_CITY_REQUEST="GET_RESTAURENT_BY_CITY_REQUEST";
export const GET_RESTAURENT_BY_CITY_SUCCESS="GET_RESTAURENT_BY_CITY_SUCCESS";
export const GET_RESTAURENT_BY_CITY_FAILURE="GET_RESTAURENT_BY_CITY_FAILURE";


export const GET_RESTAURENT_BY_USER_ID_REQUEST="GET_RESTAURENT_BY_USER_ID_REQUEST";
export const GET_RESTAURENT_BY_USER_ID_SUCCESS="GET_RESTAURENT_BY_USER_ID_SUCCESS";
export const GET_RESTAURENT_BY_USER_ID_FAILURE="GET_RESTAURENT_BY_USER_ID_FAILURE";

export const UPDATE_RESTAURENT_STATUS_REQUEST="UPDATE_RESTAURENT_STATUS_REQUEST";
export const UPDATE_RESTAURENT_STATUS_SUCCESS="UPDATE_RESTAURENT_STATUS_SUCCESS";
export const UPDATE_RESTAURENT_STATUS_FAILURE="UPDATE_RESTAURENT_STATUS_FAILURE";

export const CREATE_CATEGORY_REQUEST="CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE="CREATE_CATEGORY_FAILURE";

export const GET_RESTAURENTS_CATEGORY_REQUEST="GET_RESTAURENTS_CATEGORY_REQUEST";
export const GET_RESTAURENTS_CATEGORY_SUCCESS="GET_RESTAURENTS_CATEGORY_SUCCESS";
export const GET_RESTAURENTS_CATEGORY_FAILURE="GET_RESTAURENTS_CATEGORY_FAILURE";








