export const CREATE_MENU_CATEGORY_REQUEST="CREATE_MENU_CATEGORY_REQUEST";
export const CREATE_MENU_CATEGORY_SUCCESS="CREATE_MENU_CATEGORY_SUCCESS";
export const CREATE_MENU_CATEGORY_FAILURE="CREATE_MENU_CATEGORY_FAILURE";

export const GET_ALL_MENU_CATEGORY_REQUEST="GET_ALL_MENU_CATEGORY_REQUEST";
export const GET_ALL_MENU_CATEGORY_SUCCESS="GET_ALL_MENU_CATEGORY_SUCCESS";
export const GET_ALL_MENU_CATEGORY_FAILURE="GET_ALL_MENU_CATEGORY_FAILURE";

export const DELETE_MENU_CATEGORY_REQUEST="DELETE_MENU_CATEGORY_REQUEST";
export const DELETE_MENU_CATEGORY_SUCCESS="DELETE_MENU_CATEGORY_SUCCESS";
export const DELETE_MENU_CATEGORY_FAILURE="DELETE_MENU_CATEGORY_FAILURE";




