export const CREATE_ADDRESS_REQUEST="CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS="CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAILURE="CREATE_ADDRESS_FAILURE";

export const GET_ALL_ADDRESS_REQUEST="GET_ALL_ADDRESS_REQUEST";
export const GET_ALL_ADDRESS_SUCCESS="GET_ALL_ADDRESS_SUCCESS";
export const GET_ALL_ADDRESS_FAILURE="GET_ALL_ADDRESS_FAILURE";

export const GET_ADDRESS_BY_ID_REQUEST="GET_ADDRESS_BY_ID_REQUEST";
export const GET_ADDRESS_BY_ID_SUCCESS="GET_ADDRESS_BY_ID_SUCCESS";
export const GET_ADDRESS_BY_ID_FAILURE="GET_ADDRESS_BY_ID_FAILURE";

export const UPDATE_ADDRESS_REQUEST="UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS="UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE="UPDATE_ADDRESS_FAILURE";






